language: csharp
mono: none
sudo: false
dotnet: 2.1.402
script: "./build.sh --travis"
env:
  global:
    secure: Zlis37wHB7Rw5mO9po1SUA8I+mk2t4YsaQ7UcOOdCdW4AhVEzTlPpbI3nNXcu7xvqIPwSYjTwySd+gBwmNnFpI1gIPt8xw7Z3vyVDRRZo5OJKEupAfLXQCh74NT1v+2ddJJKCF5TSmoVgjPJkLLkC9x3GaqKz5NuO5Ij7T4X+CNKguK/3JBwWNcJ1mnVq9jxY8Dt51T02R1bHOqPTiFXtgN2Vi4Yj0b0RuqWnil0obCVq2nlT1+iW8ztPEDrx0MsBwsG3Thm17eNC6Ne/aEjH59jJaaXnfVSBxK5aziqXRRXgqZZi/R02lJQPegxELuJZK5DnZcdKEsvCbxaoDOox8kH9mXAwDGyvNYCsa26DgC5gKR7QFAJGrG1RmslgXhsDfPB2AKgO/6uXsOM3SxhzeyyL/prSG76/nt61hs/PesUTVQISwmuLG5g8DomqjFN8dYXhlmL9eidZeFYWqHScCxUOw4DM2CpbGsJMfSllrFwGI6Y3aPgqxYTtqiTxwoSWc5LbYxYeeijwTJgTO9rsud4kj0syXe5a/E3KjK3KOJEv9MtyoMeNYhSfWJbsH9qup6HiI5fciQODRyjm2DC9amVR1hbHazrWaQbf2H6ywISPgh89KUKpx47pUHimixNM/obidEN4fXIXAHdh2uj0t6hxmjBG7LvkXxfp4lGCVc=
